
name: Integration
on: [push, pull_request]

jobs:
  init:
    runs-on: ubuntu-latest
    container: golang:1.16-alpine
    steps:
      - uses: actions/checkout@v1
      - run: apk add --no-cache --no-progress alpine-sdk bash
      - run: .github/workflows/check-init